import React, { Component } from 'react';
import styles from './Article.css';

class Article extends Component {
  render() {
    return (
      <div className="article-container">
        <h1>Building Through the Draft</h1>
        <p>The mantra of ‘building through the draft has seen a lot of attention lately in the contemporary and now analytics-driven NFL - especially in recent drafts. While it is common conception that recent champions such as New England, Pittsburgh, Green Bay, and Baltimore are associated with this practice, other teams are now joining the party - such as the perennial doormat Cleveland Browns. The Browns, with their shiny new Harvard-laden front office led by Oakland A’s Moneyball executive himself Paul DePodesta, are drinking the analytics Kool-Aid and compiling hoards of draft picks not seen since the Jimmy Johnson-era Cowboys. The antagonist to this strategy is the difficulty in predicting individual player success in the NFL prior to and during the draft itself. It is even more difficult to compile a large number of successful draft picks in a short period of time in order to build a team that is competitive in the long term. Building a successful team becomes even further difficult in the wake of free agency, as players can leave after their fourth season (unless they are a first round pick and their team elects to pick up their 5th year option), and move on to another team for reasons varying from increased salary to potential to win a championship. In light of this, is being a team that drafts ‘successfully’ a legitimate predictor of team success in the NFL? We here at Better Odds decided to put those numbers to the test.
        </p>
        <p>We used the Approximate Value (AV) metric from profootballreference.com in an attempt to calculate the value for each draft pick made by each team from 2002 - 2015 in relation to the subsequent success of the team that drafted them. Approximate Value is a point value system that assigns a specific number of a team’s collective available points to corresponding players in order to gauge their value to that team’s successes. These successes come in the form of both on the field production like games started, games played, or points scored, as well as off the field accolades such as All-Pro or Pro Bowl selections. For more info on the AV methodology used on profootballreference.com, check out `http://www.pro-football-reference.com/blog/indexd961.html?page_id=8061`
        </p>
        <p>We used this AV metric here at Better Odds to compile an average AV number for all of the draft picks made by each team from 2002-2015. Specifically, we used what profootballreference.com calls DrAV, or AV for only the team that drafted a given player. For example, a player that was drafted by the Philadelphia Eagles in 2002 but leaves in free agency after 2006 would not have his AV included for the new team he signs with, as he was no longer accumulating AV for the team that drafted him. The average team AV was ranked and compared to the nine year winning percentage of each individual team from 2007-2015 in order to analyze for corresponding rankings in draft success and on the field victories.
        </p>
        <p>Having a five year buffer period between the original draft class used for this study and the original season used to measure win percentage was based on multiple factors. Giving a draftee a few years to develop is usually seen as the best way to help a player’s growth, as adjusting to life and play in the NFL can be both difficult and time consuming when coming from colleges running various forms of offense and defense. Furthermore, the five year window allows for draftees from the 2002 and 2003 draft classes to have potentially left their drafted teams in free agency - and not have accumulated DrAV for either their former or new team. Thus, this analyzation is formulated to gauge on the field success by measuring not only how well a team drafts, but how common it is for a team to hold onto their successful draft picks without watching them walk in free agency. Successful drafting added to roster continuity after the successful drafts is (theoretically) what brings success to NFL teams, right? Let’s check it out.
        </p>
        <h2>WINNING PERCENTAGE GRAPH</h2>
        <p>Here we have a graph of the teams ranked by winning percentage from 2007-2015. During this time frame, the mean winning percentage of all teams comes out to an even .500%. Thirteen teams had overall records below this threshold, and the remaining eighteen accumulated winning records during the given period. Despite this, the numbers show that the NFL as a whole is largely balanced:
        </p>
        <ul>
          <li>`14 of the 32 NFL teams (44%) had a winning percentage between .450 and .550`</li>
          <li>`11 of the 32 NFL teams were below the .450 threshold`</li>
          <li>`7 of the 32 NFL teams were above the .550 mark`</li>
        </ul>
        <p>
          Even a casual fan would most likely be able to point out the teams in the top tier with winning percentage greater than .550 - New England, Green Bay, Indianapolis, Pittsburgh, Denver, New Orleans, and Baltimore. These teams not only were successful during the regular season, but combined to win 6 of the 9 Super Bowls from 2007-2015, and four times during this span one of those teams was on the losing end of the big game. One thing noticeable about those teams is the frequent presence of a top tier quarterback such as Tom Brady or Peyton Manning. While it is common knowledge that a team needs good quarterback play to succeed in the NFL, what about the rest of the team that is placed around them by the front office?
        </p>
        <h2>AV GRAPH</h2>
        <p>As you can see, only three of the seven top tier teams by winning percentage ranked in the top ten (or thirteen, for that matter) in average AV. New Orleans, New England, and Indianapolis were mediocre at best during the given drafts, and Denver sinks all the way to number 27 in AV rankings from 2002-2015. While the successes of the aforementioned seven teams can be attributed to many factors, consistent success in the draft is not necessarily one of them. The signings of veteran players like Peyton Manning have a major effect on a team’s success, and players drafted before the 2002 mark (such as Tom Brady) also had a major effect on their team’s success without being counted in this AV metric. Coaching and management continuity - such as the Belichick regime in New England or the Tomlin regime in Pittsburgh - is also a consistent theme among the winning teams. However, continuous draft success is not a common element among all of the consistently successful teams since the 2007 season.
        </p>
        <p>However, drafting does have a correlation with the relative success of a team compared to those of its draft classes. 14 of the 32 NFL teams - including the aforementioned three in the top tier - had an AV rating within five ranking spots of their 2007-2015 winning percentage ranking in either direction. Of the fourteen teams that made up the second tier winning percentage range of .450-550, nine of those appear in the same second tier ranking level of mean AV. Of the 11 teams that had winning percentages lower than .450 from 2007-2015, 7 of those teams are also in the bottom eleven in AV ranking from 2002-2015. These are teams that many fans can recognize as being mediocre at best during the 21st century - Buffalo, Washington, Detroit, the St. Louis/Los Angeles Rams, and, of course, the Cleveland Browns.
        </p>
        <p>Oddly enough, three of the bottom tier teams were in the top ten in AV rank - Tennessee, Jacksonville, and Oakland. While all three teams had issues keeping talent in house after rookie contracts expire, they were also in the middle of transitions at quarterback. Tennessee was, in 2006, departing the Steve McNair era and beginning a new road led by Vince Young.  Jacksonville was in a similar situation after losing longtime starting quarterback Mark Brunell in the middle of the 2000’s, and has not been able to recover since despite yielding high draft picks year after year. And we all know the story of the Raiders, who have had a significant portion of their AV points coming from recent draft picks such as Derek Carr and Khalil Mack. In addition, each of teams went through multiple coaching and management changes during this time, contributing to the lack of success despite the seemingly successful drafts.</p>
        <p>The Raiders story has been a recent media marvel about how a few good drafts can turn an entire franchise around. The Cleveland Browns are seemingly next in line after making 24 picks in the previous two NFL drafts, and currently holding 12 more in 2018 that include five in the first two rounds. Their Ivy League front office is faced with turning around a franchise that has ranked 31st in winning percentage since 2007 and ranked 25th overall in average AV of draft picks from 2002-2015. Tune in next week to our examination of the draft history of the Cleveland Browns since their return to the league before the 1999 season - or, as we prefer to call it, Statistically Significant Sadness.
        </p>
      </div>
    )
  }
}
export default Article;
